# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from config import assetsURL

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 581, 771))
        self.frame.setStyleSheet("#frame{\n"
"background-color:#fff\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.DropParcelBtn = QtWidgets.QFrame(self.frame)
        self.DropParcelBtn.setGeometry(QtCore.QRect(150, 120, 201, 251))
        self.DropParcelBtn.setAutoFillBackground(False)
        self.DropParcelBtn.setStyleSheet("#DropParcelBtn{\n"
"border:2px solid;\n"
"border-color: rgb(47, 95, 171);\n"
"border-radius:15px;\n"
"background-color:none;\n"
"}")
        self.DropParcelBtn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DropParcelBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DropParcelBtn.setObjectName("DropParcelBtn")
        self.pushButton = QtWidgets.QPushButton(self.DropParcelBtn)
        self.pushButton.setGeometry(QtCore.QRect(10, 200, 181, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(250, 169, 25);\n"
"color: rgb(0, 29, 75);\n"
"font: 87 8pt \"Cairo Black\";\n"
"border-radius:7px;\n"
"cursor:pointer")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.DropParcelBtn)
        self.label.setGeometry(QtCore.QRect(50, 50, 101, 111))
        self.label.setStyleSheet("background-color:none")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(assetsURL+"/Drop-parcel.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 91, 91))
        self.label_3.setStyleSheet("background-color:none")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(assetsURL+"/Logo-icon-outline-mix.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.CollectParcelBtn = QtWidgets.QFrame(self.frame)
        self.CollectParcelBtn.setGeometry(QtCore.QRect(150, 400, 201, 251))
        self.CollectParcelBtn.setAutoFillBackground(False)
        self.CollectParcelBtn.setStyleSheet("#CollectParcelBtn{\n"
"border:2px solid;\n"
"border-color: rgb(47, 95, 171);\n"
"border-radius:15px;\n"
"background-color:none;\n"
"}\n"
"\n"
"")
        self.CollectParcelBtn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CollectParcelBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CollectParcelBtn.setObjectName("CollectParcelBtn")
        self.pushButton_2 = QtWidgets.QPushButton(self.CollectParcelBtn)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 200, 181, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(250, 169, 25);\n"
"color: rgb(0, 29, 75);\n"
"font: 87 8pt \"Cairo Black\";\n"
"border-radius:7px")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.CollectParcelBtn)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 101, 111))
        self.label_2.setStyleSheet("background-color:none")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(assetsURL+"/collect-parcel.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Drop Parcel"))
        self.pushButton_2.setText(_translate("MainWindow", "Collect Parcel"))
